# Generated by Django 4.1.13 on 2024-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='no_of_like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
