# Generated by Django 4.1.13 on 2024-09-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_posts_no_of_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='content',
        ),
        migrations.AddField(
            model_name='posts',
            name='caption',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
