# Generated by Django 4.1.13 on 2024-09-15 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_posts_content_posts_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2024, 9, 15, 14, 53, 34, 873898)),
        ),
    ]
