# Generated by Django 4.1.13 on 2024-09-15 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2024, 9, 15, 9, 31, 38, 853328, tzinfo=datetime.timezone.utc)),
        ),
    ]
