# Generated by Django 4.1.13 on 2024-09-15 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 15, 15, 9, 9, 299601)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='liked_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 15, 15, 9, 9, 300601)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 15, 15, 9, 9, 298602)),
        ),
        migrations.AlterField(
            model_name='savepost',
            name='saved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 15, 15, 9, 9, 299601)),
        ),
    ]
